version: '3.8'

services:
  yana-chatbot:
    image: ${REGISTRY:-localhost}/yana-chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - model-cache:/root/.cache/huggingface
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  model-cache:
    external: true 