version: '3'

services:
  yana-chatbot:
    build: .
    image: yana-chatbot:latest
    ports:
      - "8501:8501"
    volumes:
      - lora-model-volume:/app/lora-dino-model
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: always

volumes:
  lora-model-volume:
    external: true 