version: '3.8'

services:
  yana-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yana-chatbot
    ports:
      - "8501:8501"
    volumes:
      - yana-model-data:/app/lora-dino-model
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    image: yana-chatbot:latest

volumes:
  yana-model-data:
    external: true 