version: '3'

services:
  yana-chatbot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ../lora-dino-model:/app/lora-dino-model
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 4G

volumes:
  lora-model-volume:
    external: true 